### PR TITLE
fix: Error message handling #137

### LINKED ISSUE #137: Error message handling
We should have "nice" error output when possible. For example when:

* Generator errors return `JspmError` for all errors that don't need an error stack (non-internal errors). We only need to show the message for these.
* Similarly errors with nice messages thrown from within the CLI code itself don't need error stacks - `throw new Error('import map not found')` doesn't need to log a stack. So we distinguish between internal errors that do need a stack and _nice errors_ which can be stackless. There's a few techniques for this, I quite like the separate error class for non-stack errors `throw new JspmError(...)` where `class JspmError extends Error { constructor () { super() } }` and that's it.

### PR DESCRIPTION
**Pull request by Aslemammad**
Resolves #137

### CODE REVIEW

**Comment by Aslemammad** [comment]
Ready to merge, but failing because of the generator error.

File: src/utils.ts [hunk 1]
```diff
@@ -10,6 +10,24 @@ export class JspmError extends Error {
...
+export function wrapCommandAndRemoveStack(fn: Function) {
+  return async (...args: any[]) => {
+    try {
+      await fn(...args)
+    }
+    catch (e) {
+      stopLoading()
+      process.exitCode = 1
+      if (e instanceof JspmError || e?.jspmError) {
+        e.stack = null
```
Comment (guybedford) [inline src/utils.ts:22]: Why is this necessary?

```suggestion
```

File: src/utils.ts [hunk 2]
```diff
@@ -10,6 +10,24 @@ export class JspmError extends Error {
...
+        console.error(e.message)
```
Comment (guybedford) [inline src/utils.ts:23]:
```suggestion
        console.error(`ERR: ${e.message}`)
```
