### PR TITLE
fix:  link install test #129

### LINKED ISSUE #129: link install test
Self-hosting is always a great test:

```
jspm install jspm=./ --env=deno
```

_plus_ a Deno or Node.js execution of the above to ensure it can run itself, something like:

```
deno --unstable -A --importmap importmap.json jspm.js install jspm=./ --env=deno
```

where `importmap.json` is the full import map for Deno that runs JSPM itself.

### PR DESCRIPTION
**Pull request by Aslemammad**
Resolves #129

### CODE REVIEW

File: test.js [hunk 1]
```diff
@@ -0,0 +1,3 @@
+import chalk from 'chalk'
```
Comment (guybedford) [inline test.js:1]: Let's move this file into a `test/fixtures` folder please.

**Review by guybedford — APPROVED** [review]
Looks good with change, thanks.
