### PR TITLE
Some fixes for the release 

### LINKED ISSUE #113: Unknown commands + no args should post help

### LINKED ISSUE #114: Remove short commands for now
`jspm i`

### LINKED ISSUE #115: Running install with no args when no import map exists
There is no valid use case for this - so it's probably a mistake.

Rather, we should give the user a warning or a message or an error, telling them how to use install properly.

For example (when no importmap.json exists)

```
jspm install

Warning: No packages provided to install, creating an empty importmap.json.
```

### LINKED ISSUE #116: Installing animation
See eg ora. Nice to have a progress bar.

### LINKED ISSUE #117: Inject CLI help
This needs to be improved. Eg `-o` option isn't used so shouldn't even be there. `--stdout` as well maybe? Needs to be checked.

### LINKED ISSUE #119: jspm inject does-not-exist.html
Breaks with ENOENT.

We should either create the HTML file or provide a nice error.

### LINKED ISSUE #120: add a new "env" key to the import map
This will allow Deno and browser workflows to be running side by side without users having to always provide the `--env` flags. It also makes it very clear exactly how import maps represent conditional environment resolutions and users will then understand that.

1. The environment is now taken from the importmap as its `env` property, with the default environment of browser development only applying if there is none.
2. When saving an import map (not injecting), the full `env` list is saved into the import map under an `env` array
3. When adding the `--env` flag, it combines with the existing `env` list - either adding or removing environment names (for `no-...`). This should even work for custom unknown environment names - `--env mycustomname` and `--env no-mycustomname`. The new final list then persists just like always

With this, we can have `jspm install` retain the environment, with `jspm install --env production` and `jspm install --env deno` _switching_ the environment, and persisting that switch.

### PR DESCRIPTION
**Pull request by Aslemammad**
- [x] Resolves #120 
- [x] Resolves #119 
- [x] #118 
- [x] Resolves #117 
- [x] Resolves #116 
- [x] Resolves #115 
- [x] Resolves #114
- [x] Resolves #113

### CODE REVIEW

File: src/utils.ts [hunk 1]
```diff
@@ -44,26 +43,35 @@ export async function getInputMap(flags: Flags) {
...
     switch (name) {
       case 'no-module':
-      case 'no-node':
       case 'no-browser':
         env.splice(env.indexOf(name.slice(3)), 1)
         break
-      case 'browser':
-        env.splice(env.indexOf('node'), 1)
-        env.push('browser')
-        break
```
Comment (guybedford) [inline src/utils.ts:60]: This shouldn't be removed.

File: src/utils.ts [hunk 2]
```diff
@@ -44,26 +43,35 @@ export async function getInputMap(flags: Flags) {
...
+  }
+}
+
 export function getEnv(flags: Flags) {
   const env = ['development', 'browser', 'module']
   const envFlags = (flags.env || '').split(',').map(e => e.trim()).filter(Boolean)
   for (const name of envFlags) {
     switch (name) {
       case 'no-module':
-      case 'no-node':
```
Comment (guybedford) [inline src/utils.ts:53]: It should be possible to pass `no-node`.

File: src/utils.ts [hunk 3]
```diff
@@ -44,26 +43,35 @@ export async function getInputMap(flags: Flags) {
...
         break
-      case 'browser':
-        env.splice(env.indexOf('node'), 1)
-        env.push('browser')
-        break
       case 'production':
         env.splice(env.indexOf('development'), 1)
         env.push('production')
         break
+      case 'deno':
```
Comment (guybedford) [inline src/utils.ts:69]: Deno + Browser _CAN_ work.
